[features]
seeds = false
[programs.localnet]
fmp = "F1EJHnyEDWfbTs1bM36an7szd8ftuXJZHL4oFw9mxaiZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/asdf/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
