name: Publish evm javascript package to npmjs
on:
  push:
    tags: evm-*

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/validate-package-version-and-git-tag
        with:
          prefix: refs/tags/evm-

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: ./.github/actions/pnpm

      - name: build and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd evm \
          && pnpm install --filter . \
          && pnpm run build \
          && pnpm publish --no-git-checks
