name: Publish client-sdk to npmjs
on:
  push:
    tags: client-sdk-*

jobs:
  publish_evm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/validate-package-version-and-git-tag
        with:
          prefix: refs/tags/client-sdk-

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: ./.github/actions/pnpm

      - name: build and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install \
          && pnpm exec turbo build-ts \
          && cd client-sdk \
          && npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" \
          && pnpm publish --no-git-checks --access public
